name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsecp256k1-dev libsodium-dev python3 golang
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.uv/bin" >> $GITHUB_PATH

    - name: Build
      run: |
        make && sudo make install

    - name: Run Python tests
      run: |
        cd examples/py
        make test
        make fuzz

    - name: Run Go tests
      run: |
        cd examples/go
        make test
