name: Run tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libsecp256k1-dev libsodium-dev python3 golang

        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install secp256k1 libsodium python3 go

        fi
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.uv/bin" >> $GITHUB_PATH

    - name: Build
      run: |
        make && sudo make install

    - name: Run Python tests
      run: |
        cd examples/py
        make test fuzz

    - name: Run Go tests
      run: |
        cd examples/go
        make test
